[zh]
languageName = "简体中文"
title = "羊羽无寒"
weight = 2
lang = "zh"

[zh.params.sidebar]
subtitle = "彻底意识到自己的无知是每一次进步的前奏"
[zh.params.comments.giscus]
lang = "zh-CN"

[en]
languageName = "English"
title = "Yangyuwuhan"
weight = 1
lang = "en"

[en.params.sidebar]
subtitle = "To be fully conscious of one's ignorance is the prelude to every real advance."
[en.params.comments.giscus]
lang = "en"
